# Generated by Django 5.0 on 2024-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
