# Generated by Django 5.0 on 2024-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reservation_reservationmenuitem_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
