# Generated by Django 5.0 on 2024-01-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reservation_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
    ]
