# Generated by Django 5.0 on 2024-01-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_table_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
    ]
